### ISSUE TITLE
Backward synchronization doesn’t work

### ISSUE THREAD

**Issue by ArchangeGabriel** [peder2tm/sved#4]
But I don’t know why… Anything I should be looking at?

**Comment by ArchangeGabriel** [comment]
My mistake, the cursor is moved just not the view. Is that expected or a bug?

**Comment by peder2tm** [comment]
Thanks for reporting this.
The plugin basically runs
```execute "edit! +LINE " . fnameescape("SOURCE")```
through the remote job interface.
I have had a look and the behaviour seems to depend on which version of vim you are using:
In neovim the view jumps immediately, in gvim the view jumps when the windows gets focus and in vim the view does not jump until you move around.
But if I manually invoke ```execute "edit! +10 somefile.txt"``` in vim it jumps immediately as well. Maybe there is a way to fix this.

**Comment by ArchangeGabriel** [comment]
Sorry about that lack of details, I’m indeed using vim. Maybe I should just switch to neovim instead…

Anyway, the problem isn’t fixed as of 8.0.1127 which is the version I’m using currently.

**Comment by peder2tm** [comment]
I have tried the git version of vim (vim-git 8.0.1129.1.g2e6ab1872) and the bug is still there. However it seems to redraw the screen correctly if the edit commands is for a new file that is not already open in a buffer.

**Comment by MeisterLLD** [comment]
Hello ! Any news on that ? The problem seems to be still here in vim.

**Comment by peder2tm** [comment]
Executing "redraw" after the edit command seems to work. Feel free to reopen issue if it doesn't work for you.

**Comment by ArchangeGabriel** [comment]
Works for me, thanks! Very nice to see this bug fixed. :)
