### ISSUE TITLE
Backward sync doesn't work with NVIM

### ISSUE THREAD

**Issue by amalikmichael** [peder2tm/sved#6]
When i use your script with vim, forward and backward search work as expected. However, when I use it with nvim, only forward search works. Nothing happens when i ctrl+click in evince. Any ideas what can be going wrong?

btw: awesome script, thanks! 

update: issue is fixed when i use vim-plug to install the plugin rather than manual installation.

**Comment by peder2tm** [comment]
I am also using NVIM and it should be working.
It sounds weird that it worked after installing with vim-plug and not before.
My first thought was that it could be something with getting the wrong path for the python script, but then forward sync would not work either.
If you see the problem again you can enable logging by changing the last line of `evinceSync.py` to `main(True)`, which will create log files in your home directory. That way we can tell if the backward sync daemon is doing something or not.

**Comment by highlando** [comment]
Had to came back to this issue after a system upgrade. Ubuntu 20.04 <-- 22.04.
Turned out that I had to reinstall `pynvim` to have the backward mode running.
